name: gallerize
description: Flutter package for creating Flutter Gallery-like gallery/demo for your package/widget.
version: 0.4.0
repository: https://github.com/WieFel/gallerize

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlighting: ^0.9.0+11.8.0
  google_fonts: ^6.2.1
  highlighting: ^0.9.0+11.8.0

dev_dependencies:
  flutter_lints: ^5.0.0


screenshots:
  - description: 'Start page of the gallerize app'
    path: screenshots/info.png
  - description: 'Preview of the widget'
    path: screenshots/preview.png
  - description: 'Code of the widget'
    path: screenshots/code.png

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
